// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DescriptionsToTokens(arg1) {
  return window['go']['main']['App']['DescriptionsToTokens'](arg1);
}

export function Dump(arg1) {
  return window['go']['main']['App']['Dump'](arg1);
}

export function EncodeImagesFromPath(arg1) {
  return window['go']['main']['App']['EncodeImagesFromPath'](arg1);
}

export function GeneratePrompt() {
  return window['go']['main']['App']['GeneratePrompt']();
}

export function GetAvailableLocalModels() {
  return window['go']['main']['App']['GetAvailableLocalModels']();
}

export function GetGenerateImageConfigValue() {
  return window['go']['main']['App']['GetGenerateImageConfigValue']();
}

export function GetGeneratePromptConfigValue() {
  return window['go']['main']['App']['GetGeneratePromptConfigValue']();
}

export function GetTrainingConfigValue() {
  return window['go']['main']['App']['GetTrainingConfigValue']();
}

export function SelectImages() {
  return window['go']['main']['App']['SelectImages']();
}

export function StartImageTraining(arg1) {
  return window['go']['main']['App']['StartImageTraining'](arg1);
}

export function StoreGenerateImageConfigValue(arg1) {
  return window['go']['main']['App']['StoreGenerateImageConfigValue'](arg1);
}

export function StoreGeneratePromptConfigValue(arg1) {
  return window['go']['main']['App']['StoreGeneratePromptConfigValue'](arg1);
}

export function StoreTrainingConfigValue(arg1) {
  return window['go']['main']['App']['StoreTrainingConfigValue'](arg1);
}
