// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {structs} from '../models';

export function CheckAppConfig():Promise<void>;

export function CheckIfOllamaIsRunning(arg1:string):Promise<boolean>;

export function CheckIfPythonIsInstalled():Promise<boolean>;

export function ConfigureUserProjectsFile(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DescriptionsToTokens(arg1:string,arg2:string):Promise<string>;

export function Dump(arg1:any):Promise<void>;

export function EncodeImagesFromPath(arg1:Array<string>):Promise<Array<string>>;

export function GenerateImage(arg1:string,arg2:string):Promise<string>;

export function GeneratePrompt(arg1:string,arg2:string):Promise<string>;

export function GetAvailableLocalModels():Promise<structs.LocalModelResponseArray>;

export function GetCurrentProjectDetail():Promise<structs.UserProjectItem>;

export function GetGenerateImageConfigValue(arg1:string):Promise<structs.ConfigGenerateImage>;

export function GetGeneratePromptConfigValue(arg1:string):Promise<structs.ConfigGeneratePrompt>;

export function GetPOVText(arg1:string):Promise<string>;

export function GetTrainingConfigValue(arg1:string):Promise<structs.ConfigTraining>;

export function GetUserProjectsList():Promise<Array<structs.UserProjectItem>>;

export function HandleCreateNewProject(arg1:string,arg2:boolean):Promise<void>;

export function IsPlatformMac():Promise<boolean>;

export function ResetPOVText(arg1:string):Promise<void>;

export function SaveImage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectImages():Promise<Array<string>>;

export function SetPOVFile(arg1:string):Promise<void>;

export function SetSelectedProject(arg1:string):Promise<void>;

export function StartImageTraining(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function StoreGenerateImageConfigValue(arg1:string,arg2:structs.ConfigGenerateImage):Promise<void>;

export function StoreGeneratePromptConfigValue(arg1:string,arg2:structs.ConfigGeneratePrompt):Promise<void>;

export function StorePOVText(arg1:string,arg2:string):Promise<void>;

export function StoreTrainingConfigValue(arg1:string,arg2:structs.ConfigTraining):Promise<void>;
