// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Dump(arg1:any):Promise<void>;

export function EncodeImagesFromPath(arg1:Array<string>):Promise<Array<string>>;

export function GetGeneratePromptConfigValue():Promise<main.AppConfig>;

export function SelectImages():Promise<Array<string>>;

export function StoreGeneratePromptConfig(arg1:main.AppConfig):Promise<void>;
