// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Dump(arg1:any):Promise<void>;

export function EncodeImagesFromPath(arg1:Array<string>):Promise<Array<string>>;

export function GetGenerateImageConfigValue():Promise<main.ConfigGenerateImage>;

export function GetGeneratePromptConfigValue():Promise<main.ConfigGeneratePrompt>;

export function GetTrainingConfigValue():Promise<main.ConfigTraining>;

export function SelectImages():Promise<Array<string>>;

export function StartImageTraining():Promise<string>;

export function StoreGenerateImageConfigValue(arg1:main.ConfigGenerateImage):Promise<void>;

export function StoreGeneratePromptConfigValue(arg1:main.ConfigGeneratePrompt):Promise<void>;

export function StoreTrainingConfigValue(arg1:main.ConfigTraining):Promise<void>;
