// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAppConfig() {
  return window['go']['main']['App']['CheckAppConfig']();
}

export function CheckIfOllamaIsRunning(arg1) {
  return window['go']['main']['App']['CheckIfOllamaIsRunning'](arg1);
}

export function CheckIfPythonIsInstalled() {
  return window['go']['main']['App']['CheckIfPythonIsInstalled']();
}

export function ConfigureUserProjectsFile(arg1) {
  return window['go']['main']['App']['ConfigureUserProjectsFile'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DescriptionsToTokens(arg1, arg2) {
  return window['go']['main']['App']['DescriptionsToTokens'](arg1, arg2);
}

export function Dump(arg1) {
  return window['go']['main']['App']['Dump'](arg1);
}

export function EncodeImagesFromPath(arg1) {
  return window['go']['main']['App']['EncodeImagesFromPath'](arg1);
}

export function GenerateImage(arg1, arg2) {
  return window['go']['main']['App']['GenerateImage'](arg1, arg2);
}

export function GeneratePrompt(arg1, arg2) {
  return window['go']['main']['App']['GeneratePrompt'](arg1, arg2);
}

export function GetAvailableLocalModels() {
  return window['go']['main']['App']['GetAvailableLocalModels']();
}

export function GetCurrentProjectDetail() {
  return window['go']['main']['App']['GetCurrentProjectDetail']();
}

export function GetGenerateImageConfigValue(arg1) {
  return window['go']['main']['App']['GetGenerateImageConfigValue'](arg1);
}

export function GetGeneratePromptConfigValue(arg1) {
  return window['go']['main']['App']['GetGeneratePromptConfigValue'](arg1);
}

export function GetPOVText(arg1) {
  return window['go']['main']['App']['GetPOVText'](arg1);
}

export function GetTrainingConfigValue(arg1) {
  return window['go']['main']['App']['GetTrainingConfigValue'](arg1);
}

export function GetUserProjectsList() {
  return window['go']['main']['App']['GetUserProjectsList']();
}

export function HandleCreateNewProject(arg1, arg2) {
  return window['go']['main']['App']['HandleCreateNewProject'](arg1, arg2);
}

export function IsPlatformMac() {
  return window['go']['main']['App']['IsPlatformMac']();
}

export function ResetPOVText(arg1) {
  return window['go']['main']['App']['ResetPOVText'](arg1);
}

export function SaveImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2, arg3);
}

export function SelectImages() {
  return window['go']['main']['App']['SelectImages']();
}

export function SetPOVFile(arg1) {
  return window['go']['main']['App']['SetPOVFile'](arg1);
}

export function SetSelectedProject(arg1) {
  return window['go']['main']['App']['SetSelectedProject'](arg1);
}

export function StartImageTraining(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartImageTraining'](arg1, arg2, arg3);
}

export function StoreGenerateImageConfigValue(arg1, arg2) {
  return window['go']['main']['App']['StoreGenerateImageConfigValue'](arg1, arg2);
}

export function StoreGeneratePromptConfigValue(arg1, arg2) {
  return window['go']['main']['App']['StoreGeneratePromptConfigValue'](arg1, arg2);
}

export function StorePOVText(arg1, arg2) {
  return window['go']['main']['App']['StorePOVText'](arg1, arg2);
}

export function StoreTrainingConfigValue(arg1, arg2) {
  return window['go']['main']['App']['StoreTrainingConfigValue'](arg1, arg2);
}
